spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: Amey2020
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle12cDialect
    
    
   
        
    
  

